## 第二题 

In [4]:
import numpy as np
np.random.seed(1)
X = np.random.randint(1, 10, size=30)

In [5]:
X

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5, 6, 3, 5, 3, 5, 8, 8, 2, 8, 1, 7, 8,
       7, 2, 1, 2, 9, 9, 4, 9])

In [11]:
X = X.reshape(10,-1)

In [12]:
X

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5],
       [8, 8, 2],
       [8, 1, 7],
       [8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]])

In [13]:
last1 = X[:,-1]

In [14]:
last1

array([6, 2, 3, 3, 5, 2, 7, 2, 9, 9])

In [15]:
last1 <= 3

array([False,  True,  True,  True, False,  True, False,  True, False,
       False])

In [16]:
X

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5],
       [8, 8, 2],
       [8, 1, 7],
       [8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]])

In [17]:
last1[last1 <= 3] = 0

In [18]:
last1[(last1 > 3) & (last1 <=6)] = 1

In [19]:
last1[last1 > 6] = 2

In [20]:
last1

array([1, 0, 0, 0, 1, 0, 2, 0, 2, 2])

In [21]:
X

array([[6, 9, 1],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 1],
       [8, 8, 0],
       [8, 1, 2],
       [8, 7, 0],
       [1, 2, 2],
       [9, 4, 2]])