In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.3'

## python array

array ,数组对象，可指定传入参数的类型

In [3]:
import array

In [4]:
array.array('i',list(range(1,10)))

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = array.array('i',list(range(1,10)))

In [6]:
arr

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])

## numpy.ndarray

In [7]:
nparr = np.array(list(range(1,10)))

In [8]:
nparr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
nparr[5] = 111

In [10]:
nparr

array([  1,   2,   3,   4,   5, 111,   7,   8,   9])

In [11]:
nparr[5] = 6

In [12]:
nparr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
nparr.dtype

dtype('int32')

In [14]:
nparr2 = np.array([1,2,3],dtype=float)  #array方法可以通过修改属性dtype来强制改变序列内元素的类型

In [15]:
nparr2.dtype

dtype('float64')

In [16]:
nparr2

array([1., 2., 3.])

In [17]:
import numpy as np

In [18]:
a = np.arange(10)

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a.dtype

dtype('int32')

## 矩阵和随机数的生成

In [21]:
#np.zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
#shape
np.zeros(shape = (3,4),dtype = int) #初始化一个3行5列的矩阵

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.full((3,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [25]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [50]:
#等差数列
#import numpy as np
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## 生成随机数

In [27]:
np.random.randint(1,10)

9

In [28]:
np.random.randint(1,10,size = (3,3))

array([[6, 8, 6],
       [8, 1, 9],
       [3, 2, 5]])

## ndarray基本操作


In [29]:
A = np.arange(10)

In [30]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
A = np.ones(10)

In [32]:
A

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
A = np.ones(shape=(3,3),dtype = int)

In [34]:
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
A.ndim #获取数组维度

2

In [36]:
A.shape #获取矩阵的形状

(3, 3)

In [37]:
A.size #获取元素个数

9

In [38]:
#reshape 修改数组维度
a = np.arange(10)

In [39]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
a.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 多维数组的取值

In [42]:
X = np.arange(15).reshape(3,5)

In [43]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
X[0,1]

1

In [45]:
X[0,0]

0

## 二维数组的切片操作

In [46]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
#取前2行，前三列
X[0:2,0:3]  #0可以省略

array([[0, 1, 2],
       [5, 6, 7]])